apiVersion: v1
kind: Service
metadata:
  name: anvil
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: anvil
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.anvil.port | int }}
  type: {{ .Values.service.type }}
